[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs-18_x", "npm"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    "echo 'Frontend build completed'"
]

[start]
cmd = "python main.py"
