[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs-18_x"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    "source /opt/venv/bin/activate && pip install -r requirements.txt",
    "npm install -g pnpm",
    "cd frontend && cp package.light.json package.json && pnpm install"
]

[phases.build]
cmds = [
    "cd frontend && pnpm run build",
    "echo 'Lightweight frontend build completed'"
]

[start]
cmd = "source /opt/venv/bin/activate && python main.py"
