[phases.setup]
nixPkgs = [
    "python39", 
    "python39Packages.pip", 
    "python39Packages.setuptools",
    "nodejs-18_x",
    "npm"
]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r backend/requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "echo 'Full-stack application setup completed'"
]

[start]
cmd = "python main.py"

[variables]
PYTHONPATH = "."
NODE_ENV = "production"
PORT = "3000"
HOST = "0.0.0.0"

[providers]
python = "3.9"
