[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "nodejs-18_x"]

[phases.install]
cmds = [
    "pip install -r backend/requirements.txt",
    "cd frontend && npm install"
]

[start]
cmd = "python main.py"
