[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs-18_x"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "npm install -g pnpm",
    "cd frontend && pnpm install"
]

[phases.build]
cmds = [
    "cd frontend && pnpm run build",
    "echo 'Frontend build completed'"
]

[start]
cmd = "python main.py"
