# DiffSinger MVP Configuration
# MVP簡易版 - ダミー実装用

acoustic_model:
  checkpoint: "checkpoints/acoustic/model_ckpt_steps_160000.ckpt"
  config: "checkpoints/acoustic/config.yaml"

vocoder:
  checkpoint: "checkpoints/vocoder/model_ckpt_steps_280000.ckpt"
  config: "checkpoints/vocoder/config.yaml"

audio:
  sample_rate: 44100
  hop_size: 512
  win_size: 2048
  n_mel: 80

output:
  format: "wav"
  bit_depth: 16
  normalize: true
  default_path: "outputs/demo.wav"
